# Generated by Django 5.0.1 on 2024-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "service_user",
            },
        ),
        migrations.AddConstraint(
            model_name="serviceuser",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
