# Generated by Django 5.0.1 on 2024-05-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_userpointshistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
                ("points_change", models.IntegerField(default=0)),
                ("points_sum", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.serviceuser",
                    ),
                ),
            ],
            options={
                "db_table": "user_points",
            },
        ),
        migrations.AddConstraint(
            model_name="userpoints",
            constraint=models.UniqueConstraint(
                fields=("user", "version"), name="unique_user_version"
            ),
        ),
    ]
